<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(DotnetVersion)</TargetFramework>
        <AssemblyName>Xilium.CefGlue.Common</AssemblyName>
        <RootNamespace>Xilium.CefGlue.Common</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageId>CefGlue.Common$(PackageSuffix)</PackageId>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>

    <ItemGroup>
        <None Include="BaseCefBrowser.cs" />
    </ItemGroup>

    <ItemGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '(^|;)HAS_NLOG($|;)'))">
        <PackageReference Include="NLog" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CefGlue.Common.Shared\CefGlue.Common.Shared.csproj">
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
            <IncludeAssets>CefGlue.Common.Shared.dll</IncludeAssets>
        </ProjectReference>

        <ProjectReference Include="..\CefGlue\CefGlue.csproj">
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
            <IncludeAssets>CefGlue.dll</IncludeAssets>
        </ProjectReference>
    </ItemGroup>
</Project>
