<?xml version="1.0" encoding="utf-8"?>
<Project>
    <ItemGroup Condition="'$(Platform)' == 'x64'">
        <PackageReference PrivateAssets="None" Include="RawCef.Binaries.Windows64.Release" />
        <PackageReference PrivateAssets="None" Include="RawCef.Binaries.Macosx64.Release" />
        <PackageReference PrivateAssets="None" Include="RawCef.Binaries.Linux64.Release" />
    </ItemGroup>
    
    <ItemGroup Condition="'$(Platform)' == 'ARM64'">
        <PackageReference PrivateAssets="None" Include="RawCef.Binaries.Windowsarm64.Release" />
        <PackageReference PrivateAssets="None" Include="RawCef.Binaries.Macosarm64.Release" />
        <PackageReference PrivateAssets="None" Include="RawCef.Binaries.Linuxarm64.Release" />
    </ItemGroup>
</Project>